[package]
name = "chat-room"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "=0.7.4"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bcrypt = "0.15"
tower-http = { version = "0.5", features = ["fs"] }